version: 2
jobs:
  site-deploy:
    docker:
      - image: node:8.10
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}
            - source-v1-
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
         name: Building React site
         command: npm run build
      - attach_workspace:
          at: build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages
            git config user.email "vutsalsinghal@gmail.com"
            git config user.name "vutsalsinghal"
            cp README.md .gitignore build
      - add_ssh_keys:
          fingerprints:
            - "c0:6b:69:ad:c2:34:a9:ab:1a:32:90:55:a4:6a:97:88"
      - run:
          name: Deploy React app to gh-pages
          command: gh-pages --dist build --branch master --message "[skip ci] Updated build files"
      - save_cache:
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"

workflows:
  version: 2
  build:
    jobs:
      - site-deploy:
          filters:
            branches:
              only: code